### PR TITLE
Merge toSignedSSVMessage functions

### PR DESCRIPTION
**Pull request by MatheusFranco99**
This PR merges the already implemented utility in `SSVMessageToSignedSSVMessage` to `PartialSignatureMessagesToSignedSSVMessage`.

### CODE REVIEW

**Comment by y0sher** [comment]
@MatheusFranco99 aren't you removing this function here https://github.com/ssvlabs/ssv-spec/pull/435 ?

**Comment by MatheusFranco99** [comment]
@y0sher 
Yes. Let's wait here. Due to different comments in the PR, I ended up creating two PRs changing the same thing 😅
@GalRogozinski 
Should this be removed as in https://github.com/ssvlabs/ssv-spec/pull/435 or merged as here? (if not removed, I need to update 435).

**Comment by GalRogozinski** [comment]
I would just merge and solve conflicts

**Comment by GalRogozinski** [comment]
Closing this due to #435

**Pull request closed without merging**
