### PR TITLE
Complete SignedSSVMessage tests

### PR DESCRIPTION
**Pull request by MatheusFranco99**
## Overview

This PR adds missing tests for `SignedSSVMessage`.

#### SSV
- [x] consensus: SignedSSVMessage with no signers
- [x] consensus: SignedSSVMessage with non-unique signers
- [x] consensus: SignedSSVMessage with a zero signer
- [x] consensus: SignedSSVMessage with no signatures
- [x] consensus: SignedSSVMessage with empty signature
- [x] consensus: SignedSSVMessage with different length of signers and signatures
- [x] consensus: SignedSSVMessage with a nil SSVMessage
- [x] post consensus: SignedSSVMessage with no signatures
- [x] post consensus: SignedSSVMessage with empty signature
- [x] post consensus: SignedSSVMessage with no signers
- [x] post consensus: SignedSSVMessage with different lengths of signers and signatures
- [x] pre consensus: SignedSSVMessage with no signatures
- [x] pre consensus: SignedSSVMessage with empty signature
- [x] pre consensus: SignedSSVMessage with no signers
- [x] pre consensus: SignedSSVMessage with different lengths of signers and signatures

#### Types
- [x] SignedSSVMessage with no signers
- [x] SignedSSVMessage with no signatures
- [x] SignedSSVMessage with different lengths of signers and signatures
- [x] SignedSSVMessage with non unique signers

### CODE REVIEW

**Comment by GalRogozinski** [comment]
we have tests for wrong signatures?

**Comment by MatheusFranco99** [comment]
@GalRogozinski 
Yes

**Comment by GalRogozinski** [comment]
We seem to have some redundancy with those tests...
Both QBFT and types/partialSig tests pretty much concentrate on the outer-wrapper `msg.Validate()` function and pretty much test the same thing.

In `ssv` with the MsgProcessingSpecTest we pretty much do the same checks all over again, just in the context of the entire processing.

We need to have a discussion on how we do this properly...
Do we want to have those `MsgSpecTest` check all the validation cases and have another test that proves that the `Validate` function is called?
Maybe we can have only `MsgProcessingTests`?

I think we should open an issue and discuss this...
But before I do, do you have a good justification to have redundancy?

**Comment by GalRogozinski** [comment]
Currently my opinion is that it is nice to have validation seperated from MsgProcessing..
But we need to speak with @moshe-blox to make sure we won't be making the implementation less safe

**Comment by GalRogozinski** [comment]
@MatheusFranco99 
in the meanwhile let's just have only MsgPRocessing Tests so move the QBFT tests to `ssv/runner/consensus` and delete the duplicate type tests

**Comment by MatheusFranco99** [comment]
@GalRogozinski 
Done

**Comment by GalRogozinski** [comment]
Merging but maybe later clean up according to #448

**Pull request merged**
