### PR TITLE
Validators per operator cap: 500 to 1000

### PR DESCRIPTION
**Pull request by MatheusFranco99**
## Overview

This PR implements the spec changes associated with the update of the number of validators per operator from 500 to 1000.

Namely, it changes the number of signatures allowed in the `PartialSignatureMessages` structure.

### CODE REVIEW

**Review by GalRogozinski — APPROVED** [review]
Just in the description. link to the SIP

**Comment by GalRogozinski** [comment]
@MatheusFranco99 
btw, please add a PR on top of #491 
don't change 491 since it will be a fork

**Review by alan-ssvlabs — APPROVED** [review]

**Comment by MatheusFranco99** [comment]
@GalRogozinski 
My implementation is already adjusted to min(2*validators, validators + sync_committee_size). So I think we don't need a PR on top of it

**Review by moshe-blox — APPROVED** [review]
LGTM 🔥

**Pull request merged**
